create database ash;
drop database ashwin;

USE BMS;

CREATE TABLE CUSTOMER_PERSONAL_INFO
(
CUSTOMER_ID varchar(5),
CUSTOMER_NAME varchar(50),
DATE_OF_BIRTH DATE,
GAURDIAN_NAME VARCHAR(50),
ADDRESS VARCHAR(50),
CONTACT_NO INT(50),
MAIL_ID VARCHAR(50),
GENDER CHAR(5),
MARTIAL_STATUS VARCHAR(50),
IDENTITY_DOC_TYPE VARCHAR(50),
ID_DOC_NO VARCHAR(50),
CITIZENSHIP VARCHAR(50),
CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY (CUSTOMER_ID)

);

DROP TABLE CUSTOMER_PERSONAL_INFO;

SHOW TABLES ;
SELECT * FROM CUSTOMER_PERSONAL_info;


/*--second_table--*/
create table CUSTOMER_REFERENCE_INFO
(
CUSTOMER_ID VARCHAR(50),
REFERENCE_ACC_NAME VARCHAR(50),
REFERENCE_ACC_NO VARCHAR(50),
REFERENCE_ACC_ADDRESS VARCHAR(50),
RELATION VARCHAR(50),
constraint CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
constraint CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);
DROP TABLE CUSTOMER_REFERENCE_INFO;

/*third table*/
create table BANK_INFO
(
BANK_NAME VARCHAR(50),
IFSC_CODE VARCHAR(50),
BRANCH_NAME VARCHAR(50),
constraint BANK_INFO_PK primary key(IFSC_CODE)
);

/* 4TH TABLE*/

CREATE TABLE ACCOUNT_INFO
(
ACCOUNT_NO bigint(50),
CUSTOMER_ID VARCHAR(50),
ACCOUNT_TYPE VARCHAR(50),
REGESTRATION_DATE VARCHAR(50),
ACTIVATION_DATE VARCHAR(50),
IFSC_CODE VARCHAR(50),
INTREST_DECIMAL VARCHAR(50),
INITIAL_DEPOSIT bigint(50),
constraint ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);



INSERT INTO BANK_INFO( BANK_NAME,IFSC_CODE,BRANCH_NAME)VALUES('BOB','BARBGHA01','GHATKOPAR');
INSERT INTO BANK_INFO( BANK_NAME,IFSC_CODE,BRANCH_NAME)VALUES('BOB','BARBSION02','SION');
INSERT INTO BANK_INFO( BANK_NAME,IFSC_CODE,BRANCH_NAME)VALUES('SBI','SBIKURLA03','KURLA');
INSERT INTO BANK_INFO( BANK_NAME,IFSC_CODE,BRANCH_NAME)VALUES('HDFC','HDFCPAREL04','PAREL');
INSERT INTO BANK_INFO( BANK_NAME,IFSC_CODE,BRANCH_NAME)VALUES('ICICI','ICI05','CHEMBUR');

SELECT * from BANK_INFO;


INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GAURDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTITY_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)VALUES('C0001','ASHWIN SAVANE','2001-10-14','ARUN SAVANE','R.NO-18 L.B.SROAD MUMBAI','9892','ASH@GMAIL.COM','MALE','UNMARRIED','PANCARD','18542697','INDIA');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GAURDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTITY_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)VALUES('C0002','ARYA SAVANE','2011-7-10','ARUN SAVANE','R.NO-18 L.B.SROAD MUMBAI','7777','ARYA@GMAIL.COM','FEMAL','UNMARRIED','PANCARD','87412365','INDIA');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GAURDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTITY_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)VALUES('C0003','ARUN SAVANE','1984-11-26','LAXMISAVANE','R.NO-18 L.B.SROAD NAVI-MUMBAI','4877','ARUN@GMAIL.COM','MALE','MARRIED','AADHAR','874563','INDIA');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GAURDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTITY_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)VALUES('C0004','JACK BUTLER','1999-8-1','WILL BUTTLER','LONDON STREET','0000','JACK@GMAIL.COM','FEMAL','MARRIED','VOTER','5486','U.K');
INSERT INTO CUSTOMER_PERSONAL_INFO(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GAURDIAN_NAME,ADDRESS,CONTACT_NO,MAIL_ID,GENDER,MARTIAL_STATUS,IDENTITY_DOC_TYPE,ID_DOC_NO,CITIZENSHIP)VALUES('C0005','ARCHER GAYLE','1992-10-1','JOFRA','WEST-INDIES','1111','ARCHER@GMAIL.COM','MALE','UNMARRIED','PAASS','1854','U.S.A');

select * FROM CUSTOMER_PERSONAL_INFO;